### ISSUE TITLE
Conditions not redirecting to correct next page

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#109]
**Describe the bug**
After creating an inline condition on a link and assigning it (separate bug #110 ), in preview mode it does not resolve the condition correctly 

**To Reproduce**
1. Go to designer
2. Create a page (page A) with a yes/no field
3. Create 2 other pages (page B, page C) that links to page A
4. Add a condition to link A-B. When yes, go to B
5. Preview the form
6. Select 'yes' or 'no' on page A and continue
7. Both options resolve to page B 

**Expected behavior**
Condition should redirect to next page correctly

**Screenshots**

**Repository**
 - designer
 - runner

**Desktop (please complete the following information):**
likely a node issue
- Node 12

**Comment by jenbutongit** [comment]
@andymoody this bug came up in a show&tell prep. would you know what the issue might be?

**Comment by andymoody** [comment]
I've just checked this on master and it seems to work absolutely fine as described.

**Comment by jenbutongit** [comment]
@andymoody not sure at all. I reckon it is fairly up to date though. if it's running locally for you, then I guess something has gone wrong with the deploy config/s. Thanks for looking!

**Comment by jenbutongit** [comment]
note: to anyone picking up this issue, message me on slack or email. I'll send over the broken config.

**Comment by endamccormack** [comment]
p1.

**Comment by TheSpartan1980** [comment]
@endamccormack now we have 3 pages linked by default this is no longer an issue.
