### ISSUE TITLE
Creating an inline condition on a link does not assign it to the link

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#110]
**Describe the bug**
Creating an inline condition on a link does not assign it to the link, however it is created.

**To Reproduce**
1. go to designer
2. create a page with a component which can be used for conditions (yes/no for example)
3. create another page and link them
4. click on the link
5. create a condition inline
6. click save
7. see that the condition is not assigned to the link
8. in edit conditions, the new condition is listed

**Expected behavior**
When creating a condition inline, it should assign to the link.

**Screenshots**

**Repository**
 - Designer

**Desktop (please complete the following information):**
Universal issue

**Comment by andymoody** [comment]
@jenbutongit again, this seems to work just fine in master for me, at least locally

**Comment by jenbutongit** [comment]
Curious. thanks for 🕵️‍♂️

**Comment by TheSpartan1980** [comment]
Retested, issue no longer exists.
