### ISSUE TITLE
Run lighthouse against designer

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#126]
**Is your feature request related to a problem? Please describe.**
more a11y!

**Describe the solution you'd like**
In `runner/test/audit` there's a script that will spin up headless chrome to run a11y checks. We should add this to CI and to the designer. 

**Describe alternatives you've considered**

**Additional context**

story points: 1
_please change if higher!_

**Comment by endamccormack** [comment]
P3

**Comment by adamdavies1** [comment]
#744
