### ISSUE TITLE
Manual accessibility testing

### ISSUE THREAD

**Issue by TheSpartan1980** [XGovFormBuilder/digital-form-builder#129]
**Is your feature request related to a problem? Please describe.**
Ascertain the current accessibility of the GUI builder against the WCAG standard.

**Describe the solution you'd like**
Manually run the GUI builder through aXe, Wave and other accessbility tools in addition to testing the usability of the application. Screenreaders should also be employed to get feel for how much work needs to be factored into the backlog to meet the accessibility standard we've currently been set. 

Over time we should track the number of issues related to accessibility to enusre they're getting addressed and document process we will take going forward. 

**Describe alternatives you've considered**
It may be possible to automate some of these activites going forward once we have decided what we're going to use in terms of automation. However there are still elements of this work that will remain manual regardless of what is automated, we need to able to track this over a period of time. 

**Additional context**
https://www.deque.com/axe/
https://wave.webaim.org/
https://www.freedomscientific.com/products/software/jaws/

**Comment by endamccormack** [comment]
This has been resolved.
