### ISSUE TITLE
Use govuk-react-jsx components

### ISSUE THREAD

**Issue by bertrandmc** [XGovFormBuilder/digital-form-builder#139]
We have added [govuk-react-jsx](https://github.com/surevine/govuk-react-jsx) dependency which allows us to replace the components inside `designer/govuk-react-components`. 

**Describe the solution you'd like**
I want to use govuk-react-jsx components instead of those  inside `designer/govuk-react-components` folder so we have less code to mantain. 

**Describe alternatives you've considered**
To keep and maintain the existing components.

**Comment by jenbutongit** [comment]
#158

**Comment by endamccormack** [comment]
P3
