### ISSUE TITLE
Review CI Test Signal

### ISSUE THREAD

**Issue by bertrandmc** [XGovFormBuilder/digital-form-builder#144]
**Describe the bug**
CI doesn't not receive the right signal whenever the test phase crashes and instead it is assuming "PASS" eventhough no tests have run. See CI Status [here](https://app.circleci.com/pipelines/github/XGovFormBuilder/digital-form-builder/1409/workflows/f7dcfdbd-155b-4e43-8953-f1f232d1acce/jobs/4570)

**Expected behavior**
CI Test phase should only pass when all tests have passed.

**Screenshots**
![Screenshot 2020-10-06 at 16 26 16](https://user-images.githubusercontent.com/2582353/95222819-d01c6780-07f0-11eb-92b6-779d0af97abb.png)

**Repository**
 - designer

**Comment by endamccormack** [comment]
This issue has been resolved. @bertrandmc will post pull requrest
