### ISSUE TITLE
Refactors

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#173]
**Is your feature request related to a problem? Please describe.**
These are a list of refactors that would improve the developer experience, and performance of the app. 

## Designer 
- [x] [in progress] stop passing `data` down and use context 
  - data context has been created
- [x] use reducer to apply changes to data model
  - reducers wont trigger rerenders
  - this way we can centralise how components, lists etc changes should be handled
- [x] rewrite class components as function components
  - It makes it easier to access context and use reducers
  - makes the code reusable. there is a lot of duplicated code doing the same/similar thing
  - also makes it easier to test!!!
- [x] stop mutating component prop directly
  - deprecate `updateComponent(component, modifier, updateModel)` everywhere. in most cases it is making changes to this.props.component. It is causing a faux-stateful render update from what I can tell
- [x] rewrite tests
  - most of the tests are only testing if the initial render is ok. it is not testing for state changes and if the business logic is ok. at the moment a lot of the tests are just checking if prop in -> prop.key.value out. which is probably going to be fine.. react has done a good job with testing react 

## Engine
- [ ] #106

**Comment by bertrandmc** [comment]
Also related https://github.com/XGovFormBuilder/digital-form-builder/pull/171
