### ISSUE TITLE
"reactify" forms

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#18]
**Is your feature request related to a problem? Please describe.**
- currently saving relies on submitting a form, which is fine, but causes some issues in testing when window.FormData is required

**Describe the solution you'd like**
This can be gradually as the forms are touched by other features. 
- update forms so on input change sets a state
- onsubmit just grabs data from state rather than window.FormData

**Describe alternatives you've considered**
- we can leave it as is. for testing the window.FormData calls will just have to be stubbed

**Additional context**
- [conversation/thread](https://gitter.im/XGovFormBuilder/community?at=5ef313453a0d3931faaebf80) with @andymoody

**Comment by endamccormack** [comment]
resolved
