### ISSUE TITLE
Designer - Max call stack exceeded when page A linked with page B and vice versa

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#219]
**Describe the bug**
When page A and page B link to each other in both directions (A to B, B to A), the designer will crash with a max call stack error

**To Reproduce**

**Expected behavior**

**Screenshots**

**Repository**

- designer 

**Desktop (please complete the following information):**

- universal

**Comment by jonnywyatt** [comment]
@jenbutongit are you still seeing this? I couldn't replicate it.
1. created a new form
2. dragged the arrow from page 1 to page 2
3. dragged another arrow from page 2 to page 1

No errors in the console. Exported JSON is:
```
{
  "startPage": "/first-page",
  "pages": [
    {
      "title": "First page",
      "path": "/first-page",
      "components": [],
      "next": [
        {
          "path": "/summary"
        }
      ]
    },
    {
      "title": "Summary",
      "path": "/summary",
      "controller": "./pages/summary.js",
      "components": [],
      "next": [
        {
          "path": "/first-page"
        }
      ]
    }
  ],
  "lists": [],
  "sections": [],
  "metadata": {},
  "fees": [],
  "outputs": [],
  "version": 1,
  "conditions": []
}
```

![image](https://user-images.githubusercontent.com/471250/102223529-bc6e3b00-3edc-11eb-85c0-7745e7aa74b9.png)

**Comment by jenbutongit** [comment]
@alison0 might know more!

**Comment by alison0** [comment]
Can you setup conditions on the links and try those?

I ported over our base code from original digital forms and had to refactor the conditions.

I'll retest too.

Thanks

**Comment by alison0** [comment]
[testlinks_3.txt](https://github.com/XGovFormBuilder/digital-form-builder/files/5697254/testlinks_3.txt)

**Comment by alison0** [comment]
Hi can you change this file's extension back to json and try this example? This breaks the designer if you select a link and reproduces our issue.

thanks

**Comment by jonnywyatt** [comment]
I'll take a look, thanks
