### ISSUE TITLE
Schema versioning

### ISSUE THREAD

**Issue by andymoody** [XGovFormBuilder/digital-form-builder#22]
Break out a shared 'model' library, incorporating the best / necessary bits from designer and engine.

The 'model' library should be responsible for translating historical versions into the latest schema compatible with the current code.
Consider explicit version numbers for easy identification of migrations that need to be applied.
Can joi help us here?

**Comment by jenbutongit** [comment]
@andymoody is this complete? or only partially? I assume some of it was done in #121?

**Comment by andymoody** [comment]
I think it's done
