### ISSUE TITLE
Error when adding a date condition

### ISSUE THREAD

**Issue by jonnywyatt** [XGovFormBuilder/digital-form-builder#224]
**Describe the bug**
JS error thrown when attempting to add a date condition

**To Reproduce**

1. Create a new form
2. Add a 'Date field' component and save
3. Click Edit conditions then Add condition
4. Start adding a new condition for the date component you created

Browser JS error is thrown - `Class constructor be cannot be invoked without 'new'`
in inline-conditions-definition-values.js

**Repository**

- designer

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- Version 87

**Comment by jenbutongit** [comment]
Is this fixed now @jonnywyatt?

**Comment by jonnywyatt** [comment]
I can't replicate, closing
