### ISSUE TITLE
Re-ordering of list items doesn't work

### ISSUE THREAD

**Issue by andymoody** [XGovFormBuilder/digital-form-builder#25]
**Describe the bug**
Re-ordering of items in a list does not appear to work.

**To Reproduce**
1. Go to 'Edit Lists'
2. Click on any list or add a new list
3. Ensure at least 2 items are present
4. Try to drag items around with the drag handles
5. Nothing happens

**Expected behavior**
The list items should be re-ordered and this should be reflected on the screen. The changes should only be persisted on submit.

**Screenshots**

**Repository**
 - designer

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**
Note that initially I was receiving errors around the items list being undefined (state initialisation didn't allow for this possibility for a new list), and errors around duplicate key values where item-${item.value} always evaluated to 'item-' for new items. I have resolved these issues.

**Comment by andy-ickleford-squash** [comment]
@jenbutongit, did you fix this?

**Comment by jenbutongit** [comment]
Nope! was i trigger happy?

**Comment by andy-ickleford-squash** [comment]
Thanks!

**Comment by endamccormack** [comment]
Primary issue fix. Some styling fixes yet to be completed.
