### ISSUE TITLE
Bugs / UX issues / missing features from prototyping FCDO emergency alerts

### ISSUE THREAD

**Issue by jonnywyatt** [XGovFormBuilder/digital-form-builder#290]
Replicating the [FCDO emergency alerts prototype](https://fcdo-alerts-prototype.herokuapp.com/) using form builder (it's currently built using gov.uk prototyping kit).

All bugs on latest Chrome / Mac OS.

### Redirected to 404 URL when adding a field name

1. Add paragraph component
2. Error shown - ‘add field name’
3. Select ‘Add’
You’re redirected to [this url](https://digital-form-builder-designer.herokuapp.com/app#/field-name) which is 404

### From ‘Add page’, redirected to preview when adding a condition
1. Add page
2. Select ‘Link from’
3. Select ‘Define a new condition’
Preview of the first page in the form is launched in the same tab so you lose your changes

### Trying to return to Designer home page but keep being redirected to test form
1. Redirected to https://digital-form-builder-runner.herokuapp.com/test/uk-passport?visit=qYIZAt9Dfs
2. Try to return to https://digital-form-builder-runner.herokuapp.com/
3. Redirected automatically to URL in step 1

## UX issues
- Add Radios field component - ‘This is the title text displayed on the page’ - confusing as we’re adding a component not a page?
- (minor) - Edit page - if path is already populated eg for a summary page, and you update the Page title, no need to automatically overwrite the path?
- 'Edit summary behaviour' button at the top, maybe makes more sense as a contextual button within the summary page object?
- How do I know my new form is saved somewhere?

**Comment by jenbutongit** [comment]
> This is the title text displayed on the page’ - confusing as we’re adding a component not a page?
this is a seriously long standing issue which we never fixed properly/thought of a fix for. The behaviour was that if you only had one component, then the title of that component would be the title of the page. You would see that if you added another component, it would/should use the title set on the Page.

**Comment by jenbutongit** [comment]
>Redirected to 404 URL when adding a field name 
I think this may be resolved by #285. @kakanisridhar will know more

**Comment by kakanisridhar** [comment]
Hi jon , I introduced hashrouting and react router , that broke many parts of application as we are using # in many anchor tags and we are not  calling preventDefault on click of anchor.
I am working on a fix to change HashRouter to BrowserRouter, so bear with me till tomorrow end

**Comment by jonnywyatt** [comment]
Thanks. If an anchor tag only has # as it's href, it should probably be a button anyway as it's JS-only functionality?

**Comment by endamccormack** [comment]
@jonnywyatt we think this issue has been resolved. Feel free to reopen this issue if it persists for you.
