### ISSUE TITLE
Missing features from prototyping FCDO emergency travel alerts

### ISSUE THREAD

**Issue by jonnywyatt** [XGovFormBuilder/digital-form-builder#291]
Replicating the [FCDO emergency alerts prototype](https://fcdo-alerts-prototype.herokuapp.com/) using form builder (it's currently built using gov.uk prototyping kit).

## Features needed

- Page titles - can they include variables eg ‘Subscribe to Emergency Alerts for <country>’
- Start page - how do we add content below the “Start now” button?
- 'Add another' - some way to build up a list of items, combined with a type-ahead search ([example](https://fcdo-alerts-prototype.herokuapp.com/country))
- 'Checkbox reveal' - https://design-system.service.gov.uk/components/checkboxes/#conditionally-revealing-content (although has one outstanding a11y issue which GDS plan to fix)
- (minor) Summary page - can we omit some answers from this. Eg if a 'guard' yes/no question prevents the user from continuing to the summary ("This service is for British National only. Please confirm (yes/no)"), no need to put the answer on the summary as it will always be yes

**Comment by jenbutongit** [comment]
@jonnywyatt  At the bottom of the readme, there's some information on how to do conditional reveals. I forget if it works with checkboxes, radio for sure. (I wouldn't recommend via the component though - best with global lists) 

- Start page - how do we add content below the “Start now” button?
  - Not possible but you can add another template - or change the current template to allow content to be shown at the bottom of the button
- 'Checkbox reveal' - https://design-system.service.gov.uk/components/checkboxes/#conditionally-revealing-content (although has one outstanding a11y issue which GDS plan to fix)
- (minor) Summary page - can we omit some answers from this. Eg if a 'guard' yes/no question prevents the user from continuing to the summary ("This service is for British National only. Please confirm (yes/no)"), no need to put the answer on the summary as it will always be yes
  - maybe the easiest way to add this is to add an option to the component `component.options.omitFromSummary`

**Comment by endamccormack** [comment]
should be raised with product team

**Comment by superafroman** [comment]
A couple more comments - 

- Page titles, new issue here: #466
- Start page: these are not meant to live in a form, they belong on gov.uk. The ability to do this in the form is only there for demoing purposes which was very reluctantly included (but is used alot so worthwhile). Regardless, new issue here #468
- Add another: this is currently possible via repeatable questions. (Can't see the example so maybe making an assumption here)
- Checkbox reveal: Jen's covered using the pattern. Another approach is to ask for the additional input on another page.
- Summary page, new issue here: #467
