### ISSUE TITLE
List items don't seem to be being filtered by condition

### ISSUE THREAD

**Issue by andymoody** [XGovFormBuilder/digital-form-builder#30]
**Describe the bug**
List items don't seem to be being filtered by condition

**To Reproduce**
1. Add a list with options 'A' and 'B'
2. Add a page with a radio field 'myField' based on the list created in step 1.
3. Add a condition based on 'myField' is 'A'
4. Add another list with some options which are controlled by the condition created in 3 and some which are not.
5. Add a page with a radio field based on the list created in step 4
6. Link the two pages
7. Go to the runner and step through the form selecting 'B' 
8. Note that the options with conditions are still displayed

**Expected behavior**
The list items protected by the condition should not be displayed

**Screenshots**

**Repository**
 - runner

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Comment by jenbutongit** [comment]
This is weird. I was working on a form a couple days ago and this was working. Have you tried with the cache being cleared? (you will have to close all browser tabs + start incognito tab)

**Comment by jenbutongit** [comment]
#35
