### ISSUE TITLE
(Optional) text does not appear for optional fields which are shown when a list item is selected

### ISSUE THREAD

**Issue by andymoody** [XGovFormBuilder/digital-form-builder#31]
To reproduce:

1. Add a list with options 'A' and 'B'. Add a 'Text Field' component to option A, and make the Text Field component optional.
2. Add a page with a radio group using the list defined in step 1.
3. Access the page in the runner and select Option A. 
4. The text field is displayed with no '(Optional)' text.

Expected outcome:

The text field should be displayed with (Optional) text

Additional Information:

From a bit of investigation it appears that the issue is actually in designer - when saving in list-edit.js we don't attempt to retrieve whether the optional / optionalText fields are set. It appears that if we do try to retrieve this we currently receive no context information about which conditional input of which list item this relates to.

**Comment by endamccormack** [comment]
forms-299

p2
