### ISSUE TITLE
Adjust app dependencies

### ISSUE THREAD

**Issue by endamccormack** [XGovFormBuilder/digital-form-builder#333]
Relates to FORMS-317

We need to improve the organisation of dependencies across all workspaces and root package.json.

Problem: This is causing bugs in CI pipeline and increasing the size of the images

Issues:
1. Some deprecated dependencies are still being installed
2. Many dev dependencies are installed as normal dependencies
3. Test related dependencies are installed in the root package.json instead of the appropriate workspace.
4. Discrepancies with dependencies versions across the workspaces
5. Root package.json references packages thats should be present only in the workspaces
6. Fix dependencies so the designer and runner can run of latest version of node

Objective:
To be able to build with a production flag set without any issues

**Comment by jenbutongit** [comment]
suggestion: 
we set the workspaces to nohoist dependencies. The way that we're building/deploying (not pnp mode and not zero install mode), we don't see that much benefit in hoisted deps. This should mean that root pkg.json should be clear of most dependencies.
