### ISSUE TITLE
Designer tech debt - defining sub-components in lists

### ISSUE THREAD

**Issue by endamccormack** [XGovFormBuilder/digital-form-builder#335]
Relates to: FORMS-319

Currently changes to the data are handled by a series of callbacks being passed down to child components which will update data (which sits at top level of the app). Because there are so many moving parts, it's getting difficult to track what is responsible for changing what and how. Changes to data will also cause the whole app to rerender. 

use reducer to apply changes to data model
reducers wont trigger rerenders
this way we can centralise how components, lists, etc changes should be handled
consolidate same type editors - some editor components are duplicated. eg, the code for editing a radio component is duplicated by the code for editing a checkbox component
remove usages of `updateComponent` function. It is changing a "stateful" variable directly. <- this should not be done because it is bypassing react's render enqueuing

**Comment by jenbutongit** [comment]
this has been addressed in #246
