### ISSUE TITLE
Add additional headers to improve application security

### ISSUE THREAD

**Issue by gautampachnandahmo** [XGovFormBuilder/digital-form-builder#350]
A security scan of the application has recommended the following headers should be introduced to improve the security of the application

- 'X-XSS-Protection' Header HTTP Security Header
- 'X-Content-Type-Options' Header HTTP Security Header
- Content Security Policy HTTP Security Header
- 'X-Frame-Options' Header HTTP Security Header
- 'Expect-CT' Header HTTP Security Header
- HTTP Header Information Disclosure HTTP Security Header

**Comment by endamccormack** [comment]
P2

**Comment by superafroman** [comment]
X-XSS-Protection, X-Content-Type-Options and X-Frame-Options are all set. The apps are also not sending any server version info or other information disclosure headers. If these are being seen maybe they are coming from infrastructure. So remaining headers are:

 - Content Security Policy
 - Expect-CT

I would expect Expect-CT to be set wherever SSL is managed, this should not be within these apps.
