### ISSUE TITLE
Enhance cookie security

### ISSUE THREAD

**Issue by gautampachnandahmo** [XGovFormBuilder/digital-form-builder#352]
Security scan of the application has recommended the following updates to the cookies

- Add Secure Flag
- Add SameSite Flag
- Add HttpOnly Flag

**Comment by jenbutongit** [comment]
@gautampachnandahmo which app please?

**Comment by endamccormack** [comment]
P2

**Comment by superafroman** [comment]
These are set for runner, designer doesn't use cookies.
