### ISSUE TITLE
Add transport security policy

### ISSUE THREAD

**Issue by gautampachnandahmo** [XGovFormBuilder/digital-form-builder#353]
A security scan has recommended adding transport security policy to the application.

Solution:
https://www.tenable.com/plugins/was/98056

**Comment by jenbutongit** [comment]
@gautampachnandahmo was this reported for runner or designer? for the runner, if the environment is configured with sslKey and sslCert we turn on TLS.

We also have these options set up 
```
 security: {
        hsts: true,
        xss: true,
        noSniff: true,
        xframe: true,
      },
```

**Comment by endamccormack** [comment]
P2

**Comment by superafroman** [comment]
Designer and runner have HSTS enabled.
