### ISSUE TITLE
Designer lists - table headings are misaligned 

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#44]
**Describe the bug**
Looks like the drag handle has been added in the wrong place so the table headings/table data are shifted across one

**To Reproduce**
1. Go to designer
2. Click on edit lists, and edit a list
![Screenshot 2020-07-08 at 13 40 58](https://user-images.githubusercontent.com/22080510/86920116-22ca8280-c121-11ea-9974-a04879f42634.png)

**Expected behaviour**
text should line up with text input, value with value, etc
**Repository**
 - Designer

**Desktop (please complete the following information):**
 - OS: OSX 10.15.14 (likely to be across board) 
 - Browser: chrome, safari 
 - Version: Chrome - 83.0.4103.116 (Official Build) (64-bit), safari: Version 13.1

**Comment by aslam-cyb** [comment]
Hi Jen, 

This issue has already been fixed?

![image](https://user-images.githubusercontent.com/61144002/87042990-53c3b980-c1ec-11ea-86b7-d737aead9b4e.png)

**Comment by jenbutongit** [comment]
Ah I see, I guess it hasn’t been deployed yet. Could you tag the PR it was fixed and closed the issue then? Thanks!
