### ISSUE TITLE
Fix 'Complex Code' issue in model\src\conditions\inline-condition-model.ts

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#454]
[CodeFactor](https://www.codefactor.io/repository/github/xgovformbuilder/digital-form-builder/overview/master) found an issue: Complex Code

It's currently on:
[model\src\conditions\inline-condition-model.ts](https://www.codefactor.io/repository/github/xgovformbuilder/digital-form-builder/source/master/model/src/conditions/inline-condition-model.ts)

**Comment by superafroman** [comment]
@jenbutongit  Seems to have a nice green A in codefactor now, can this be closed?

**Comment by jenbutongit** [comment]
imho nope - complex code is still being flagged, even though it's showing A. 

It's a 500 line file, it's hard to understand what's going on. there's also issues to do with hand cracked implementations "abstract" via class, when we can just use ts natives, which is adding to the complexity.
