### ISSUE TITLE
Support dynamic page headings / titles

### ISSUE THREAD

**Issue by superafroman** [XGovFormBuilder/digital-form-builder#466]
**Is your feature request related to a problem? Please describe.**
Currently page headings / titles are static.

**Describe the solution you'd like**
To be able to include a variable that references an answer already provided, e.g. `Subscribe to emergency alerts for ${country}`.

Arguably it would be good to be able to do this in any block of text.

Originally raised in #291

**Comment by jenbutongit** [comment]
This is implemented for #677

**Comment by jenbutongit** [comment]
I think we should enable this in the designer.. but will need some thinking around it. Let's add it into the runner for now?

**Comment by jenbutongit** [comment]
This was added as part of https://github.com/XGovFormBuilder/digital-form-builder/pull/1142.

`ALLOW_USER_TEMPLATES` must be set to true (defaults to off). 

Variables can be used in content fields and page titles. The field must also have the `exposeToContext` flag turned on. 

More detail in the [templating.md](https://github.com/XGovFormBuilder/digital-form-builder/blob/main/docs/runner/templating.md) docs
