### ISSUE TITLE
Create condition flyout off edge of screen

### ISSUE THREAD

**Issue by superafroman** [XGovFormBuilder/digital-form-builder#484]
**Describe the bug**
When creating a condition via the Edit List flyout, the create condition flyout is laid out off the left side of the screen.

**To Reproduce**

1. Create a new form
2. Add a field component to page 1
3. Click the link between pages 2 and 3 to edit it
4. Click "Define condition"
5. See layout issue

**Expected behavior**
The full define condition layout is visible.

**Repository**

- designer

**Comment by jenbutongit** [comment]
resolved by #465
