### ISSUE TITLE
It's far too easy to click "Close" on a flyout when you mean to save.

### ISSUE THREAD

**Issue by superafroman** [XGovFormBuilder/digital-form-builder#487]
**Describe the bug**
This is a usability bug rather than a code bug.

When editing something in a flyout, the "Close" link in the top right is the default place to go to end what you're doing. But it cancels your changes. 

It would prevent a user doing this to remove "Close" and instead add a "Cancel" link next to the "Save" button.

**Comment by jenbutongit** [comment]
Needs rethink, we have "delete" links in some areas. If a user is expecting delete/cancel next to the save button, that's an easy mistake to make. I think we need something like a "you have unsaved changes"
