### ISSUE TITLE
Irrelevant question still evaulated in conditions

### ISSUE THREAD

**Issue by superafroman** [XGovFormBuilder/digital-form-builder#503]
**Describe the bug**
If an applicant answers a number of questions and then goes back to a previous answer and changes it, if that previous answer change results in a different path through the form questions that are no longer relevant are still available to conditions being evaluated.

**To Reproduce**

1. Create a form that contains a branch, e.g. "Have you been married before?", "Yes" goes to another page, "What is your current marital status", This goes to a 3rd page "What you need to apply". If the branch "Have you been married before?" is answered "No" it goes straight to "What you need to apply". 
2. Add a text input component to "What is your current marital status" that can be used in a condition.
3. Add some content to "What you need to apply" that is only displayed if your current marital status is equal to "Divorced"
4. Go through the form, answer Yes then enter "Divorced", you will see you conditional content on "What you need to apply". Then click "back" and "back" again answering "No" this time and you will still see your conditional component.

**Expected behavior**
If the branch is updated to "No" all properties only relevant to that branch are ignored.

**Repository**

- runner

**Comment by jenbutongit** [comment]
Apologies, I missed this, looks critical! :( I'll cross post on HO Jira.

**Comment by gstevenson** [comment]
@superafroman - we're going to pick this up and take a look this sprint

**Comment by MCrawleyHomeOffice** [comment]
PR raised, pending review.

https://github.com/XGovFormBuilder/digital-form-builder/pull/540

**Comment by TheSpartan1980** [comment]
@superafroman is your issue now fixed?

**Comment by jenbutongit** [comment]
yep <3
