### ISSUE TITLE
Autocomplete missing on name

### ISSUE THREAD

**Issue by alison0** [XGovFormBuilder/digital-form-builder#534]
As raised on https://gitter.im/XGovFormBuilder/community - May 07 @15:59

Is there any autocomplete that we can set on/off - again this has been flagged in the accessibility report which says - There is no autocomplete attribute set to the input fields. This forces users to re-enter previously entered information, which can be laborious to some users. As the collected details do not get saved during the journey, if the user gets timed out it is even more important to set this attribute. This issue was found to affect the Firefox browser the worst. Although the autocomplete is on the <form> it does not transfer the expected autofill details to the correct input fields.

**To Reproduce**

1. Go to 'Any input text field on a form, this one mentioned Name.'
2. Click on 'the field and start typing - autocomplete is not offered.'

**Expected behavior**
Autocomplete would kick in

**Screenshots**
n/a

**Repository**

- runner

**Desktop (please complete the following information):**
Not working at all so all below apply

**Smartphone (please complete the following information):**
Not working at all so all below apply

**Additional context**
This has been highlighted in a recent accessibility report for the service and would apply across all forms text entry fields.

**Comment by jenbutongit** [comment]
Reopening this, autocomplete fields aren't being passed onto fields like address/telephone
