### ISSUE TITLE
Incorrect Field Mark-up – [GDS]

### ISSUE THREAD

**Issue by alison0** [XGovFormBuilder/digital-form-builder#535]
As raised on https://gitter.im/XGovFormBuilder/community - May 07 @16:25

Form related accessibility report issue - Incorrect Field Mark-up – [GDS]. The request for name form was not marked up correctly to current GOV.UK Design System. This is on the form itself so would be applicable to all users - please see details below.

The page requesting the details of the user’s name was incorrectly marked up as per current
GOV.UK Design System guidelines. The top-level content and the heading which
corresponds to the title have all been placed inside the heading. There are also other
attributes missing, such as spellcheck and autocomplete (which is at
DAC_Form_Autocomplete ). This can confuse users who expect GOV.UK services to be the
same with titles and headings matching and can delay users who need to confirm they are
on the correct page.

**To Reproduce**

1. Go to 'Name text field on a form'
2. Check display - The top-level content and the heading which corresponds to the title have all been placed inside the heading

**Expected behaviour**
To be to GOV.UK Design System guidelines

**Screenshots**
![image](https://user-images.githubusercontent.com/19928656/117636805-11a33580-b179-11eb-819d-aafacd66d67b.png)

**Repository**

- designer and runner

**Desktop (please complete the following information):**
All of the below

**Smartphone (please complete the following information):**
All of the below

**Additional context**
n/a

**Comment by superafroman** [comment]
@alison0 I'm missing something with this one - do you have a URL I can go to to look at your form with the incorrect markup?

From the screenshot this *looks* the same as the design system. And from a very quick test I think I'm getting the correct markup. But there are a couple of cases where this markup changes so I'm just wanting to confirm against your service.

Thanks!

**Comment by alison0** [comment]
@superafroman try this link https://www.express-an-interest-in-a-flight.service.csd.fcdo.gov.uk/algeria-20210422/express-your-interest-in-a-repatriation-flight-from-country?
This is the production environment.  The titles and headings have been reworked in Dev already. Thanks

**Comment by superafroman** [comment]
Form markup is 
```
<div class="govuk-form-group" data-children-count="1">
  <h1 class="govuk-label-wrapper">
    <label class="govuk-label govuk-label--xl" for="name">
      <span class="govuk-caption-xl">Your details</span> Your Name
    </label>
    
  </h1>

  
  
  <div id="name-hint" class="govuk-hint">
    Please enter your full name
  </div>

<input class="govuk-input govuk-input--width-20" id="name" name="name" type="text" aria-describedby="name-hint">
</div>
```

**Comment by alison0** [comment]
@jenbutongit just checking this one is not contrary to #536 - the caption should be outside of the h1 heading, yes?
Plus should spellcheck be on? Autocomplete has now been taken care of via #534, yes? Thanks

<div class="govuk-form-group">
  <label class="govuk-label" for="name">
    Name
  </label>
  <input class="govuk-input" id="name" name="name" type="text" spellcheck="true" autocomplete="name"></div>
