### ISSUE TITLE
Caption included in headings

### ISSUE THREAD

**Issue by alison0** [XGovFormBuilder/digital-form-builder#536]
As raised on https://gitter.im/XGovFormBuilder/community - May 07 @16:25

The top level, or caption, has been included in the heading of the page, this is contrary to current GOV.UK Design System guidelines for a question page.

Expected behaviour 
To follow GOV.UK Design System guidelines

**Screenshots**
![image](https://user-images.githubusercontent.com/19928656/117637652-ea009d00-b179-11eb-830a-1150fc624a58.png)
**Repository**

- designer and runner

**Desktop (please complete the following information):**
All of the below

**Smartphone (please complete the following information):**
All of the below

**Additional context**
Raised on a recent accessibility report so would apply across all services

**Comment by superafroman** [comment]
@alison0 Is this another issue with markup? The current design system has no problem with sections (e.g. https://design-system.service.gov.uk/patterns/question-pages/section-headings/index.html)

**Comment by alison0** [comment]
It is complaining about the Caption - 'Your details', but as you know this is on all the questions if we include a section. Has this been past as acceptable? 
Report states "The top level, or caption, has been included in the heading of the page, this is contrary to 
current GOV.UK Design System guidelines for a question page."

The report suggests - "The page heading should relate specifically to the information being asked for on the 
current page, not any higher-level section the page is part of. The .govuk-caption should be 
placed outside the <h1>."

Is this contrary to what you are being told?

**Comment by alison0** [comment]
Apologies, not sure why that went big and bold!

**Comment by alison0** [comment]
it had put it as a h1 heading.

**Comment by jenbutongit** [comment]
@superafroman has suggested moving section title outside of h1, since it is not semantically part of the question. I'll pick this up
