### ISSUE TITLE
When filling out a form, I cannot go back and update text field to empty string 

### ISSUE THREAD

**Issue by chrishumphreys** [XGovFormBuilder/digital-form-builder#565]
**Describe the bug**
I cannot update a text input (or textarea) field value to empty string after it has previously be set to a value.

**To Reproduce**
Steps to reproduce the behavior (e.g. using [report a terrorist example form](https://digital-form-builder-runner.herokuapp.com/report-a-terrorist)):

1. Fill out the first two pages of the form  (it's ok to chose no link and no evidence).
2. On the *Additional Info* page, enter any string as a value. Click Continue.
3. On the Summary screen note the string value is displayed (as you'd expect). 
4. Press Change next to "Additional Info" field
4. Delete the value in the *Additional Info* box so it is completely empty and click continue.
5. Note the value is still set on the Summary screen.

**Expected behaviour**

The previously entered string for  *Additional Info*  should be removed.

**Additional context**

I have a feeling this is due to this code in [PageControllerBase.ts](https://github.com/XGovFormBuilder/digital-form-builder/blob/master/runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts)

```
const savedState = await cacheService.mergeState(  
                request,
                update,
                !!this.repeatField
)
```
The value of `!!this.repeatField` is passed to the nullOverride parameter of the mergeState. For non repeating fields this means a null value **will not** replace a previous value.

I changed it locally to `true` and it did then overwrite - which is what I want.

However I'm not clear of the developer's original intention with only overwriting repeating fields. It looks deliberate so I'm wondering if I'm missing something.

**Comment by jenbutongit** [comment]
hey @chrishumphreys - thanks for this.. casting my mind back, I suppose I missed this use case - it didn't come up as an issue previously. 

Have you fixed this on your fork? Maybe this is safer? 

```.js
//mergeState call
cacheService.mergeState(  
                request,
                update,
                this.repeatField
)
```

```.js
// CacheService
  async mergeState(
    request: HapiRequest,
    value: object,
    nullOverride = true,
    arrayMerge = false
  ) {
    const key = this.Key(request.yar.id, request.params.id);
    const state = await this.getState(request);
    hoek.merge(state, value, !!nullOverride, arrayMerge);
```
