### ISSUE TITLE
Running Designer Locally Fails With 500 Error 

### ISSUE THREAD

**Issue by MCrawleyHomeOffice** [XGovFormBuilder/digital-form-builder#622]
[xgovformbuilder-error120721.txt](https://github.com/XGovFormBuilder/digital-form-builder/files/6802704/xgovformbuilder-error120721.txt)

**Describe the bug**
Unable to run Designer application locally.

**To Reproduce**
Clone repo in new directory
Run "yarn" in command-line
Once completed, run "yarn build" in command-line
Once completed, run "yarn designer start" from the command-line
Browse to http://localhost:3000/

Below error is shown:
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

**Expected behavior**
Designer homepage is shown.

**Screenshots**
Attached.

<img width="823" alt="Screenshot 2021-07-12 at 16 58 31" src="https://user-images.githubusercontent.com/82369580/125319529-c3561280-e332-11eb-9398-94b59c6a04ff.png">

**Repository**
Designer.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: All
- NPM: 6.14.12
- Yarn: 2.4.0
- Node: 12.22.1

**Additional context**
Seems its searching for a designer.html which doesn't exist within the compiled "dist" directory.

<img width="304" alt="Screenshot 2021-07-12 at 16 42 58" src="https://user-images.githubusercontent.com/82369580/125317065-9d2f7300-e330-11eb-9c35-ad3cd1795ab7.png">

**Comment by neculaionutni** [comment]
Hi @jenbutongit ,

I'm having the same issue. Can you please share how did you manage to solve it?

**Comment by jenbutongit** [comment]
hey @neculaionutni, 

could you first let me know which git tag/version you are on? 

For the latest versions of XGovFormBuilder you must be running node 16. Try these steps, and show me any stack traces if you get any.

If you want to run this via yarn/node:

1. run `yarn`
2. run `yarn install model`
3. run `yarn model build`
4. run `yarn designer build`
5. run `yarn runner install`
6. run `yarn runner build`
7. run `yarn runner dev` (or `yarn runner start`)
8. run `yarn designer dev` (or `yarn designer start`).

Alternatively via docker
`docker compose up` will start redis, designer and runner.
