### ISSUE TITLE
Allow option to pre-populate a field with a query string parameter when the user is submitting a form

### ISSUE THREAD

**Issue by ziggy-98** [XGovFormBuilder/digital-form-builder#639]
**Is your feature request related to a problem? Please describe.**
Sometimes with some of our forms the user is sent from the website to the form with parameters in the url to pre-populate certain fields e.g when a user reports a missed bin collection, we send through their uprn and and the bin type so that they don't have to enter these.

**Describe the solution you'd like**
I know that some people have already developed their own workarounds for this functionality but I think it would be useful to have a standardised implementation.

The solution I have in mind is to add a new option to all fields with the "field" subtype for parameter name which, when not empty, triggers the logic to run in the runner.

I'm not sure on the best way to adapt the runner to account for this new option so I'm happy to follow other people's lead with that. I'll also work on a couple of solutions I have in mind to see whether any of them work well, or even work at all!

**Comment by jenbutongit** [comment]
https://github.com/XGovFormBuilder/digital-form-builder/tree/main/docs/adr 

could you possibly grab a template from here and fill it out on how you expect it to work? and/or a diagram? When I imagined this, it would work something like so:
0. configure runner to connect to prefilling microservice
1. user goes to `/my-service?id=abc-def-uid-123` 
2. runner detects query param `id=abc-def-uid-123` 
3. runner requests data for id from the configured microservice
4. runner fills the user state with the data received
5. redirect user to where they "got up" to, or possibly to another page/controller? 

Are you thinking of writing a microservice (that connects up to the DB)? If you've got the capacity, it would be great to publish an image (or just have an open repo) so it can be reused by other departments. 

@MCrawleyHomeOffice did a spike around this. 

also cc @superafroman - does my suggested approach sound OK?

**Comment by superafroman** [comment]
What about just using URL params? I think a microservice or redis is good for save and return or where you've got a load of data to pre-populate. But will we ever have that much data to pre-populate? And so do we need the complexity of a persistence backend in order to support pre-populating?

I think of this as something as simple as `{formStartUrl}?{fieldId1}=abc&{fieldId2}=123&{metadataKey1}=xyz`

i.e. no need for an additional property on the field, just making use of the field ID and the metadata key.

**Comment by froddd** [comment]
We originally implemented SSO-based auth with a view to being able to pre-populate form fields using the profile data for the signed-in user. 

Given the discussion above (and some other chats with @jenbutongit about a 'global' or 'user' session), it may be useful to tweak the existing session store to accept a 'global' key, alongside all the existing forms data, for any given runner. This global data could be populated using query params on form load, as suggested by @superafroman above, or on user sign-in. Field renderers could then pick into this global store to generate pre-populated data?
