### ISSUE TITLE
Allow pre-populated fields to be hidden from the user

### ISSUE THREAD

**Issue by ziggy-98** [XGovFormBuilder/digital-form-builder#640]
**Is your feature request related to a problem? Please describe.**
There are times where we'll want to have fields that contain pre-populated values that are important for the outputs of the form. In these cases we should be able to hide the field from the user so that the value exists in the form state but cannot be edited by the user. This issue is closely linked to #639.

**Describe the solution you'd like**
We can provide another option for fields to specify whether the field should be visible, which is checked by default. When this comes through to the runner, provided that we can populate the value in the form with server-side code, we could have the getFormModel function to return null in place of a FormModel.

**Describe alternatives you've considered**
I'm not hugely experienced with the system yet so it's entirely possible that I've missed something and every component is required to return a view model from that function, in which case we might have to do this another way. If this is the case I'll explore other options.

**Comment by jenbutongit** [comment]
this might be related to https://github.com/XGovFormBuilder/digital-form-builder/issues/467 also. I wonder if our mechanism for hiding fields could work for both of these features? what do you think? :)

cc @superafroman

**Comment by ziggy-98** [comment]
Definitely, I imagine that if you were to set a field to be hidden from the user while they were filling it in then you would probably want it hidden from the summary page as well.

With regards to [excluding fields from the webhook](https://github.com/XGovFormBuilder/digital-form-builder/issues/467#issuecomment-815670413), maybe we could add an option for 'excluded fields' and provide a select list of fields that have been marked as hidden, similar to the GOVNotify output's personalisations? Then in the webhook service we can check for excluded fields and remove them from the data object before doing the post request. Do you think that could work?

**Comment by jenbutongit** [comment]
at the moment FCDO only have a need to exclude a field entirely. This means omit it from view from the summary page, as well as have it removed from any web hook requests. Would it be the same for you? 

The only complexity I can see if a user would like to exclude data from one webhook and not the other (but we don't do so ¯\_(ツ)_/¯)

**Comment by ziggy-98** [comment]
There's a possibility that we would need to specify which hidden fields we wouldn't want to show on our side. For example, on our contact us form we pass through information about the service that the user needs help with, but we don't want the user to be able to change this so would hide the field. However this information is still important when passed to the CRM system so that it can be assigned to the right case worker.

Maybe we could do something where instead of choosing which fields to exclude, all hidden fields are excluded from the webhook by default, but you can specify hidden fields that you want to be passed through? Do you think that makes sense from a UX point of view or do you think that could be confusing for the user?

Actually thinking about it maybe if you don't need that functionality then we'll just keep it to ignoring all hidden fields by default and add the extra bit on separately on our forked version 😄

**Comment by jenbutongit** [comment]
It is in our backlog, so we would like it at some point! your solution sounds good to me. 

For context, we have a series of questions at the beginning of our services which will filter out of a user is eligible for this service. If a user isn't eligible, we take them to a "dead end", and they aren't able to complete the form. They're not required for the caseworkers (and irrelevant to the user if they're actually eligible, so we'd rather hide it)

**Comment by superafroman** [comment]
I think if we have data the user shouldn't be able to edit, there shouldn't be a field definition for it. We already do this with `metadata` although at the moment metadata is static there's no reason we shouldn't be able to add additional metadata to an applicant's session when they are directed to the form.

Using metadata would mean the data is not available to be edited and not shown on the summary page but is submitted to any webhooks.

I'd suggest we take the same approach to this as #639 which would mean any additional data we want to set in a form needs to already be defined in the form config, but can be overridden by the initial creation of the applicant's session. So just like a form field would need to exist to be pre-populated, the key for any additional metadata we want to set would need to exist in the form config.
