### ISSUE TITLE
Options not saving properly in state when creating or editing a component

### ISSUE THREAD

**Issue by ziggy-98** [XGovFormBuilder/digital-form-builder#641]
**Describe the bug**
When creating or editing a component, if you try to change two options, the second option will reset all of the other options.

As far as I can tell this is an issue with the [options reducer on line 18](https://github.com/XGovFormBuilder/digital-form-builder/blob/main/designer/client/reducers/component/componentReducer.options.ts#L18) It looks like it's trying to get the options from the state object:

`const { selectedComponent } = state;
const { options } = state;`

Which is returning undefined, as the options exist on the selected component, not the state:

`const { selectedComponent } = state;
const { options } = selectedComponent;`

**To Reproduce**

1. Run `yarn`
2. Run `yarn build`
3. Run `yarn designer dev`
4. Navigate to the designer in the browser and choose an existing form or create a new one
5. Add a text component or edit an existing component
6. Tick the "Hide title" box, then tick the "Make text field optional" box. You'll notice the "Hide title" box will become unticked

**Expected behavior**
When choosing one or more options, all options should remain chosen.

**Repository**

- Designer

**Desktop (please complete the following information):**

- OS: MacOS 11.2.1
- Browser: Chrome
- Version: 92

**Comment by jenbutongit** [comment]
Hey @ziggy-98 - thanks! Happy for you to open a PR for this. Let me know if you need a hand 🌟 - I probably wont be able to work on this myself for a while.. got a few other things in my backlog!

**Comment by ziggy-98** [comment]
Hey @jenbutongit - cool cool, I've fixed this locally so I'll push the change up and submit a PR at some point today 😄

**Comment by jenbutongit** [comment]
thanks! you should have permissions, so it will be easier if you create a branch on this repo rather than open a PR from a fork

**Comment by jenbutongit** [comment]
#645
