### ISSUE TITLE
Upgrade to node 16

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#659]
**Is your feature request related to a problem? Please describe.**
Title ☝️ 

Node 16 will be entering LTS (so, safe to use in production) at the end of October https://nodejs.org/en/about/releases/

**Describe the solution you'd like**
- Upgrade to node 16
   - make sure tests run as they should (and the app in general, smoke tests should cover this) 
   - update docker files to use a v16 image
   - update babel to target v16  for node environments only (so babel doesn't have to transpile some features for a compatible version) 

**Describe alternatives you've considered**

**Additional context**
We are currently recommending node 12 since node 14 has issues with node-fibers (I'm sure they can be resolved, but I'm pretty sure it's a known issue.. rebuilding the lib doesn't work >:()

**Comment by jenbutongit** [comment]
I had a little digging around and essentially the issue is `wdio/sync`. Node 16 no longer allows access to the underlying API that allowed node-fibres to work, which is what wdio/sync sync uses to handle "await"-ing. https://webdriver.io/blog/2021/07/28/sync-api-deprecation/

some solutions
1. split out the workspace into it's own repo, and keep it on node 12
2. refactor so wdio/sync is no longer required
3. refactor for cypress.io and modern js syntax

**Comment by superafroman** [comment]
My preference would be option 3.. If we split it out we have to maintain a set of tests running on a legacy framework and old version of node. And it's separate from what it's testing, so will be forgotten in further development.

I am conscious that 3 could be a bit of work though..! Can you see a way of iteratively doing this?

**Comment by jenbutongit** [comment]
@superafroman - I can't remember how many tests rely on wdio/sync.. the first option would just cypress-ify the ones that are but I suspect it might actually be all of them 😭. 

we could do a mixture of 1 & 3? Split out and when there is a PR/merge to main we can use GitHub Actions to pull and run the smoke-tests. Then refactor for cypress

**Comment by jenbutongit** [comment]
paging @TheSpartan1980 - I know you've moved on 😢 but just an FYI.. I'm not deleting tests, promise! 

I'm
1. moving the wdio smoke-tests to their own repository
2. setting up an action that can be triggered from other repos, and will remain on node 12 so wdio/sync is happy.. 
3. these tests will run on each PR, merge and nightly like they already do 
4. use cypress.io instead on the main repo. I suppose we could keep the cucumber/gherkin and replace them and switch them off in the separated repo

**Comment by TheSpartan1980** [comment]
@jenbutongit updating to chromedriver here: https://github.com/XGovFormBuilder/digital-form-builder/blob/main/smoke-tests/designer/wdio.conf.js to 99.0.4844.51 might help. Ps you can run WDIO in sync mode on node 14 LTS without issue. The WDIO are working on a codemod to transition from sync to async for version 8 from what I have read.
