### ISSUE TITLE
some menu items are using data as a prop instead of context

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#710]
> Ah, this should be using context instead of the prop but I'll open a new issue for it

_Originally posted by @jenbutongit in https://github.com/XGovFormBuilder/digital-form-builder/pull/709#discussion_r756226378_

**Is your feature request related to a problem? Please describe.**
`DataContext` should be used where possible, to prevent from prop drilling and data being out of sync 

**Describe the solution you'd like**
Most components have been converted to use `DataContext`, however some are still using the prop. Please remove any instances of `<SomeComponent data={data}>` or `this.props.data`. For class components, it should be this.context

**Comment by JamesBoadi** [comment]
Already completed [#747](https://github.com/XGovFormBuilder/digital-form-builder/pull/747)
