### ISSUE TITLE
Turn on global styles for the runner

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#716]
**Is your feature request related to a problem? Please describe.**
HTML is supported, however it can be quite easy to forget to add the classes if you do so.

**Describe the solution you'd like**
Turning on global styles will remove the need for requiring at least typography based classes https://frontend.design-system.service.gov.uk/sass-api-reference/#global-styles

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/22080510/145378651-56729354-1512-4cae-9113-6225c8c671cc.png)
steps to reproduce: 
- create a paragraph component
- use this content
  ```
   <h2>This is not GDS transport</h2>
   <div>
    <p>
      this is also still not GDS transport!
   </p>
   </div>
  ```
- preview the page

**Comment by endamccormack** [comment]
@jenbutongit I've lost my close ability. Can you close this for me? 😢

**Comment by jenbutongit** [comment]
I haven't reviewed yet, hasn't been merged yet I don't think. I'll get to it today @endamccormack
