### ISSUE TITLE
Error message on list creation

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#719]
**Describe the bug**
Error message "The list must have list items" is still displayed after a list item has been created

**To Reproduce**

1. Go to the designer
2. lists 
3. create a list with no items
4. click save
5. see error message
6. create a list item and save
7. error message still there 

**Expected behavior**
No error message after saving the list item

**Screenshots**
![image](https://user-images.githubusercontent.com/22080510/145383101-1836bc8a-f2f6-49a2-8808-bafb2ba889ee.png)

**Repository**
- designer

**Desktop (please complete the following information):**
- universal

**Smartphone (please complete the following information):**
- universal 

**Additional context**

**Comment by adamdavies1** [comment]
will take a look at this

**Comment by adamdavies1** [comment]
[719](https://github.com/XGovFormBuilder/digital-form-builder/pull/822)
