### ISSUE TITLE
Add list - cancel/close do not work

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#720]
**Describe the bug**
When creating a new list, clicking close or cancel does not work

**To Reproduce**

1. Go to the designer and create a new form
2. add a radio/checkbox component to a page
3. create a new list 
4. clicking cancel or close on "add list" does not work

**Expected behavior**
Should be able to close/cancel! 

**Screenshots**

**Repository**

- designer

**Desktop (please complete the following information):**
- universal

**Smartphone (please complete the following information):**
- universal

**Additional context**

**Comment by adamdavies1** [comment]
Picking this up
