### ISSUE TITLE
ADR 0002 amendments

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#742]
This issue for discussing any suggestions, comments, amendments to do with #741 https://github.com/XGovFormBuilder/digital-form-builder/blob/main/docs/adr/0002-save-and-return.md 

paging these issues
#561
#639
#640

**Comment by superafroman** [comment]
I'm not sure about including a new webhook endpoint in the initial `returning-user` request. This opens up a potential security issue where a 3rd party could initialise a session and set it to post data back to their own service - the applicant then thinks they're safe as they're on a recognised URL when filling in their data, but it goes off somewhere unexpected.

If it's important to be able to submit updated applications to a different webhook we could either add auth to this new endpoint, or we could probably get away with configuring a prefix that the new webhook must match.

Also, I'm not too keen on the `/returning-user` endpoint (just the naming). This endpoint could be used for pre-populating, so technically the user is new. How about `/initialise-session`? The endpoint to load their data could be `/load-session/{token}` - note here I'd also move the token from a query param to a path param, on the off chance an applicant is visiting us via a proxy that ignores query params.

Another thing to touch on is how we manage expired links. I'd suggest for a v1 we just display a page explaining the link has expired and directing the applicant to get in touch via email.

**Comment by jenbutongit** [comment]
@superafroman - we'll have to think about how to flag a webhook/output for returning users I reckon? Possibly a toggle on the output editing? i.e. "Is this webhook for prefilled sessions?" (wording tbc..). I would assume you wouldn't want to send a second confirmation email which is exactly the same or POST a duplicate user

**Comment by superafroman** [comment]
@jenbutongit I guess that's where allowing the output to be defined in the initialise-session call comes in handy. Doing it this way means the caller can define an endpoint including their own internal ID for de-duping the data. And we don't have to complicate the current outputs with any filtering or anything. We just need to validate the endpoint that's passed in is an approved URL. It'll be more flexible to do this by defining another config variable that is a prefix, or a regex, to match to the endpoint.
