### ISSUE TITLE
Feedback forms

### ISSUE THREAD

**Issue by andymoody** [XGovFormBuilder/digital-form-builder#78]
Allow users to specify form-level properties:

1) What's the form name/title?
2) Is this a feedback form? 
    If yes - disable summary page by default
              - Make any provided url context available to outcomes etc
              - Simplify the UI? There's probably no need for fees etc
    If no - Is there a URL for gathering feedback? If no then hide the feedback link in runner? If there is a URL then should we provide context (form name / path and page name / path)

**Comment by jenbutongit** [comment]
1. in my persistence branch I have a "new" page #72 
2. I don't think it needs a feedback flag right now, but hiding UI elements or showing a warning might be helpful (in case someone tries to add a pay output for some reason)
3. There is not a specific url for gathering any data. you should use the webhook output. it will collate all the questions (title and field) with the answers. if you need to provide context, you can use the metadata field
