### ISSUE TITLE
Mandatory field - Error messages are wrongly shown in the Date fields 

### ISSUE THREAD

**Issue by antoniot1501** [XGovFormBuilder/digital-form-builder#982]
When a mandatory field is not filled in by the user AND there are DATE fields configured in the form, IF the user doesn't fill in the mandatory field then the error message is displayed not only in that corresponding field, but also it is displayed wrongly in the DATE fields (see attached screenshot).

![2022-12-09 10_57_17-Section 3_ COVID-19](https://user-images.githubusercontent.com/120177950/206687992-d80c5831-79a0-4944-b3a9-5e68135a87b0.png)

**Expected behavior**
Error message should only be displayed for the mandatory field(s)

**Comment by jenbutongit** [comment]
Hi @antoniot1501.. unsure if you're still at UKHSA, but I believe we've resolved this issue as part of #1210. sorry for the delay! perhaps @george-hsa might find this useful also? 

![image](https://github.com/XGovFormBuilder/digital-form-builder/assets/22080510/0f359ea2-0453-4a16-b86f-fedb02d6a072)
